# Generated by Django 4.2.5 on 2023-10-22 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='game',
            table='home_game',
        ),
        migrations.AlterModelTable(
            name='lab',
            table='home_lab',
        ),
    ]
