# Generated by Django 4.2.5 on 2023-10-30 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_game_table_alter_lab_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='short_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='lab',
            name='abstract',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='lab',
            name='short_description',
            field=models.TextField(default=''),
        ),
    ]
